import type { FrameMeta } from "@zframes/spec/frame";

/**
 * Frame metadata, separated from components so React-free tooling (the
 * zframes CLI, catalogue export, the /zframes skill) can import this module
 * without charts, liveline, or CSS. Each frame's .tsx imports its meta from
 * here — this file is the single source of truth for the AI catalogue.
 */

import {
  priceChartMeta,
  priceLivelineMeta,
  priceTickerMeta,
  topMoversMeta,
  priceCompareMeta,
  priceEventsMeta,
  coinMoversMeta,
  breadthHistogramMeta,
  rsiMomentumMeta,
  volumeProfileMeta,
  returnCalendarMeta,
  returnDistributionMeta,
  orderBookDepthMeta,
  dominanceBarsMeta,
  indexLevelChartMeta,
  indexLevelMeta,
  indexDrawdownMeta,
  indexAnnualReturnsMeta,
  vixGaugeMeta,
} from "./schemas/markets";
import {
  tvlTreemapMeta,
  bitcoinDominanceMeta,
  dexVolumeTreemapMeta,
  dexVolumeChartMeta,
  protocolTvlTreemapMeta,
  protocolTvlChartMeta,
  protocolFeesTreemapMeta,
  marketCapTreemapMeta,
  stablecoinSupplyMeta,
  yieldScannerMeta,
  yieldDistributionMeta,
  tokenUnlockScheduleMeta,
  cryptoProfileMeta,
  cryptoDilutionMeta,
  protocolRevenueMeta,
  protocolMultiplesMeta,
  defiRevenueMeta,
  ethSupplyMeta,
  ethStakingMeta,
  etfFlowsMeta,
  trendingCoinsMeta,
  sectorPerformanceMeta,
  stablecoinChainsMeta,
  sectorTreemapMeta,
  etfFlowsChartMeta,
  nftCollectionsMeta,
  nftTreemapMeta,
  sectorBarsMeta,
  etfFlowBarsMeta,
  marketScatterMeta,
  marketBubblesMeta,
  tvlBubblesMeta,
  protocolTvlBubblesMeta,
  dexVolumeBubblesMeta,
  protocolFeesBubblesMeta,
  sectorBubblesMeta,
  nftBubblesMeta,
  moversBubblesMeta,
  sentimentGaugeMeta,
  moversBarsMeta,
  tvlBarsMeta,
  yieldScatterMeta,
  nftScatterMeta,
  dominanceGaugeMeta,
  coinMomentumHeatmapMeta,
  coinMomentumScatterMeta,
  trendingBarsMeta,
  nftActivityBarsMeta,
  trendingBubblesMeta,
  yieldRiskPieMeta,
  protocolFeesVsTvlScatterMeta,
  yieldCompositionScatterMeta,
  protocolTvlByCategoryMeta,
  protocolTvlShareAreaMeta,
  dexVolumeShareAreaMeta,
  yieldMomentumBarsMeta,
  etfIssuerTreemapMeta,
  etfIssuerBarsMeta,
  etfFlowCalendarMeta,
} from "./schemas/crypto";
import {
  btcFeesMeta,
  btcMempoolMeta,
  btcBlocksMeta,
  btcHashrateMeta,
  btcDifficultyMeta,
  miningPoolsMeta,
  lightningStatsMeta,
  btcDifficultyChartMeta,
  btcBlockSizeBarsMeta,
  mempoolFeeCurveMeta,
  miningPoolsShareMeta,
} from "./schemas/bitcoin";
import {
  mvrvMeta,
  nuplMeta,
  soprMeta,
  puellMultipleMeta,
  mayerMultipleMeta,
  piCycleMeta,
  maMultiplierMeta,
  cycleSignalsMeta,
  realizedPriceMeta,
  reserveRiskMeta,
  dexHotPoolsMeta,
  chainActivityMeta,
  dexPoolTreemapMeta,
  chainActivityBarsMeta,
  dexPoolBubblesMeta,
  dexPoolLiquidityScatterMeta,
  chainPriceMoversMeta,
  chainActivityScatterMeta,
  mvrvZscoreChartMeta,
  nuplCycleChartMeta,
  cycleValuationCompositeMeta,
  onchainOscillatorOverlayMeta,
  ethIssuanceImpactMeta,
} from "./schemas/onchain";
import {
  fundingRateChartMeta,
  fundingCalendarMeta,
  fundingDistributionMeta,
  fundingHeatmapMeta,
  openInterestMeta,
  optionsPutCallMeta,
  optionsIvMeta,
  optionsOiStrikeMeta,
  optionsChainTableMeta,
  fundingComparisonMeta,
  fundingBarsMeta,
  putCallGaugeMeta,
  oiTreemapMeta,
  ohlcvVolumeBarsMeta,
  fundingSpreadBarsMeta,
  fundingVenueHeatmapMeta,
  fundingCarryAreaMeta,
  volumeShareDonutMeta,
  volumeMoversScatterMeta,
  fundingLeaderboardBarsMeta,
  fundingCrowdingScatterMeta,
  liquidityBasisBarsMeta,
  optionsMaxPainMeta,
  optionsOiSkewMeta,
  optionsVolSpreadMeta,
  optionsFlowSkewMeta,
  optionsVolSmileMeta,
  optionsOiLadderHeatmapMeta,
  optionsMaxPainMultiMeta,
  equityOptionsOiMeta,
  equityOptionsSmileMeta,
  equityOptionsMaxPainMeta,
  equityOptionsGreeksMeta,
} from "./schemas/derivatives";
import {
  ratesBoardMeta,
  fxBoardMeta,
  inflationPulseMeta,
  financialStressMeta,
  nationalDebtMeta,
  laborMarketMeta,
  treasuryAuctionsMeta,
  yieldCurveMeta,
  dxyMeta,
  macroCalendarMeta,
  treasuryAvgRateBarsMeta,
  treasuryAuctionDemandScatterMeta,
  treasuryAuctionSizeBarsMeta,
  nyfedReferenceRateBarsMeta,
  nyfedSofrTermAveragesBarsMeta,
  nyfedFedFundsBandGaugeMeta,
  treasuryDebtCompositionAreaMeta,
  ofrStressCategoryAreaMeta,
  miseryIndexMeta,
  realWagesMeta,
  laborForceFlowMeta,
  payrollsBarsMeta,
  fxCrossHeatmapMeta,
  fxTrendChartMeta,
  dxyChartMeta,
  fxMoversBarsMeta,
  creditSpreadChartMeta,
  homePriceIndexMeta,
  mortgageRateChartMeta,
  regionalHomePricesMeta,
  metroHomeValuesMeta,
  homeValueChartMeta,
  creditQualityGapMeta,
  mortgagePaymentMeta,
  homeValueBarsMeta,
  homeValueMomentumMeta,
  homeValueScatterMeta,
  regionalHomePriceBarsMeta,
} from "./schemas/macro";
import {
  metalsBoardMeta,
  metalPriceMeta,
  metalValueMeta,
  metalPriceChartMeta,
  metalDrawdownMeta,
  metalAnnualReturnsMeta,
  metalSeasonalityMeta,
  metalVolatilityMeta,
  goldSilverRatioMeta,
  metalRatioChartMeta,
  metalCompareChartMeta,
  metalPerformanceMeta,
  metalAthMeta,
  metalFixTableMeta,
  metalMilestonesMeta,
  metalReturnDistributionMeta,
  metalsCorrelationMeta,
  metalRatioPercentileMeta,
  metalRollingCorrelationMeta,
  btcInGoldMeta,
  metalCotNetMeta,
  metalCotBreakdownMeta,
  metalCotGaugeMeta,
  metalOpenInterestMeta,
  metalRealPriceMeta,
  metalVsMacroMeta,
  commodityVolRegimeMeta,
  metalCotDisaggregatedMeta,
  metalCotConcentrationMeta,
  metalCotPercentileMeta,
  metalSpecNotionalMeta,
  metalPositioningVsPriceMeta,
  usGoldReserveMeta,
  usGoldVaultsMeta,
  tokenizedGoldMeta,
} from "./schemas/metals";
import {
  filingsFeedMeta,
  fundamentalsMeta,
  shortVolumeMeta,
  shortVolumeBarsMeta,
  capitalStructureBarsMeta,
  filingsMixMeta,
  companyProfileMeta,
  valuationMultiplesMeta,
  financialsTrendMeta,
  marginTrendMeta,
  cashflowTrendMeta,
  earningsSurpriseMeta,
  earningsCountdownMeta,
  earningsCalendarMeta,
  analystRatingsMeta,
  institutionalOwnershipMeta,
} from "./schemas/equities";
import {
  fearGreedMeta,
  newsFeedMeta,
  predictionMarketsMeta,
  fearGreedChartMeta,
  sentimentCalendarMeta,
  predictionMarketBarsMeta,
  predictionMarketScatterMeta,
  predictionMarketsBubbleMeta,
} from "./schemas/sentiment";
import {
  portfolioValueMeta,
  portfolioAllocationMeta,
  portfolioHoldingsMeta,
  portfolioMoversMeta,
  portfolioValueBarsMeta,
} from "./schemas/portfolio";
import {
  journalLogMeta,
  journalOpenMeta,
  journalResultsMeta,
  journalScoreMeta,
} from "./schemas/journal";
import {
  clockMeta,
  marketHoursMeta,
  countdownMeta,
  linkGridMeta,
  calculatorMeta,
  diceMeta,
  riskRewardMeta,
  stopwatchMeta,
  sessionProgressMeta,
  holidayCalendarMeta,
  dayMeterMeta,
  returnsProjectorMeta,
  breakevenMeta,
  checklistMeta,
  pomodoroMeta,
  customDataMeta,
} from "./schemas/tools";
import {
  noteMeta,
  imageMeta,
  heroNumberMeta,
  imageGalleryMeta,
  groupMeta,
  headingMeta,
  videoMeta,
  drawdyMeta,
  quoteMeta,
  dividerMeta,
  marqueeMeta,
  rulesCardMeta,
  breathingMeta,
  spotifyEmbedMeta,
} from "./schemas/layout";
import { dinoGameMeta, snakeMeta, flappyBirdMeta } from "./schemas/games";

export * from "./schemas/markets";
export * from "./schemas/crypto";
export * from "./schemas/bitcoin";
export * from "./schemas/onchain";
export * from "./schemas/derivatives";
export * from "./schemas/macro";
export * from "./schemas/metals";
export * from "./schemas/equities";
export * from "./schemas/sentiment";
export * from "./schemas/portfolio";
export * from "./schemas/journal";
export * from "./schemas/tools";
export * from "./schemas/layout";
export * from "./schemas/games";

/**
 * The curated agent-pickable metadata — what the CLI catalogue and the
 * /zframes skill read. Grouped by category in FRAME_CATEGORIES order (the
 * first-appearance order here is the family order `catalogueSummary`
 * presents), alphabetical within each block — insert in order.
 */
export const frameMetas: FrameMeta[] = [
  // --- markets ---
  breadthHistogramMeta,
  coinMoversMeta,
  dominanceBarsMeta,
  indexAnnualReturnsMeta,
  indexDrawdownMeta,
  indexLevelChartMeta,
  indexLevelMeta,
  orderBookDepthMeta,
  priceChartMeta,
  priceCompareMeta,
  priceEventsMeta,
  priceLivelineMeta,
  priceTickerMeta,
  returnCalendarMeta,
  returnDistributionMeta,
  rsiMomentumMeta,
  topMoversMeta,
  vixGaugeMeta,
  volumeProfileMeta,
  // --- crypto ---
  bitcoinDominanceMeta,
  coinMomentumHeatmapMeta,
  coinMomentumScatterMeta,
  cryptoDilutionMeta,
  cryptoProfileMeta,
  defiRevenueMeta,
  dexVolumeBubblesMeta,
  dexVolumeChartMeta,
  dexVolumeShareAreaMeta,
  dexVolumeTreemapMeta,
  dominanceGaugeMeta,
  etfFlowBarsMeta,
  etfFlowCalendarMeta,
  etfFlowsChartMeta,
  etfFlowsMeta,
  etfIssuerBarsMeta,
  etfIssuerTreemapMeta,
  ethStakingMeta,
  ethSupplyMeta,
  marketBubblesMeta,
  marketCapTreemapMeta,
  marketScatterMeta,
  moversBarsMeta,
  moversBubblesMeta,
  nftActivityBarsMeta,
  nftBubblesMeta,
  nftCollectionsMeta,
  nftScatterMeta,
  nftTreemapMeta,
  protocolFeesBubblesMeta,
  protocolFeesTreemapMeta,
  protocolFeesVsTvlScatterMeta,
  protocolMultiplesMeta,
  protocolRevenueMeta,
  protocolTvlBubblesMeta,
  protocolTvlByCategoryMeta,
  protocolTvlChartMeta,
  protocolTvlShareAreaMeta,
  protocolTvlTreemapMeta,
  sectorBarsMeta,
  sectorBubblesMeta,
  sectorPerformanceMeta,
  sectorTreemapMeta,
  sentimentGaugeMeta,
  stablecoinChainsMeta,
  stablecoinSupplyMeta,
  tokenUnlockScheduleMeta,
  trendingBarsMeta,
  trendingBubblesMeta,
  trendingCoinsMeta,
  tvlBarsMeta,
  tvlBubblesMeta,
  tvlTreemapMeta,
  yieldCompositionScatterMeta,
  yieldDistributionMeta,
  yieldMomentumBarsMeta,
  yieldRiskPieMeta,
  yieldScannerMeta,
  yieldScatterMeta,
  // --- bitcoin ---
  btcBlockSizeBarsMeta,
  btcBlocksMeta,
  btcDifficultyChartMeta,
  btcDifficultyMeta,
  btcFeesMeta,
  btcHashrateMeta,
  btcMempoolMeta,
  lightningStatsMeta,
  mempoolFeeCurveMeta,
  miningPoolsMeta,
  miningPoolsShareMeta,
  // --- onchain ---
  chainActivityBarsMeta,
  chainActivityMeta,
  chainActivityScatterMeta,
  chainPriceMoversMeta,
  cycleSignalsMeta,
  cycleValuationCompositeMeta,
  dexHotPoolsMeta,
  dexPoolBubblesMeta,
  dexPoolLiquidityScatterMeta,
  dexPoolTreemapMeta,
  ethIssuanceImpactMeta,
  maMultiplierMeta,
  mayerMultipleMeta,
  mvrvMeta,
  mvrvZscoreChartMeta,
  nuplCycleChartMeta,
  nuplMeta,
  onchainOscillatorOverlayMeta,
  piCycleMeta,
  puellMultipleMeta,
  realizedPriceMeta,
  reserveRiskMeta,
  soprMeta,
  // --- derivatives ---
  equityOptionsGreeksMeta,
  equityOptionsMaxPainMeta,
  equityOptionsOiMeta,
  equityOptionsSmileMeta,
  fundingBarsMeta,
  fundingCalendarMeta,
  fundingCarryAreaMeta,
  fundingComparisonMeta,
  fundingCrowdingScatterMeta,
  fundingDistributionMeta,
  fundingHeatmapMeta,
  fundingLeaderboardBarsMeta,
  fundingRateChartMeta,
  fundingSpreadBarsMeta,
  fundingVenueHeatmapMeta,
  liquidityBasisBarsMeta,
  ohlcvVolumeBarsMeta,
  oiTreemapMeta,
  openInterestMeta,
  optionsChainTableMeta,
  optionsFlowSkewMeta,
  optionsIvMeta,
  optionsMaxPainMeta,
  optionsMaxPainMultiMeta,
  optionsOiLadderHeatmapMeta,
  optionsOiSkewMeta,
  optionsOiStrikeMeta,
  optionsPutCallMeta,
  optionsVolSmileMeta,
  optionsVolSpreadMeta,
  putCallGaugeMeta,
  volumeMoversScatterMeta,
  volumeShareDonutMeta,
  // --- macro ---
  creditQualityGapMeta,
  creditSpreadChartMeta,
  dxyChartMeta,
  dxyMeta,
  financialStressMeta,
  fxBoardMeta,
  fxCrossHeatmapMeta,
  fxMoversBarsMeta,
  fxTrendChartMeta,
  homePriceIndexMeta,
  homeValueBarsMeta,
  homeValueChartMeta,
  homeValueMomentumMeta,
  homeValueScatterMeta,
  inflationPulseMeta,
  laborForceFlowMeta,
  laborMarketMeta,
  macroCalendarMeta,
  metroHomeValuesMeta,
  miseryIndexMeta,
  mortgagePaymentMeta,
  mortgageRateChartMeta,
  nationalDebtMeta,
  nyfedFedFundsBandGaugeMeta,
  nyfedReferenceRateBarsMeta,
  nyfedSofrTermAveragesBarsMeta,
  ofrStressCategoryAreaMeta,
  payrollsBarsMeta,
  ratesBoardMeta,
  realWagesMeta,
  regionalHomePriceBarsMeta,
  regionalHomePricesMeta,
  treasuryAuctionDemandScatterMeta,
  treasuryAuctionSizeBarsMeta,
  treasuryAuctionsMeta,
  treasuryAvgRateBarsMeta,
  treasuryDebtCompositionAreaMeta,
  yieldCurveMeta,
  // --- metals ---
  btcInGoldMeta,
  commodityVolRegimeMeta,
  goldSilverRatioMeta,
  metalAnnualReturnsMeta,
  metalAthMeta,
  metalCompareChartMeta,
  metalCotBreakdownMeta,
  metalCotConcentrationMeta,
  metalCotDisaggregatedMeta,
  metalCotGaugeMeta,
  metalCotNetMeta,
  metalCotPercentileMeta,
  metalDrawdownMeta,
  metalFixTableMeta,
  metalMilestonesMeta,
  metalOpenInterestMeta,
  metalPerformanceMeta,
  metalPositioningVsPriceMeta,
  metalPriceChartMeta,
  metalPriceMeta,
  metalRatioChartMeta,
  metalRatioPercentileMeta,
  metalRealPriceMeta,
  metalReturnDistributionMeta,
  metalRollingCorrelationMeta,
  metalSeasonalityMeta,
  metalSpecNotionalMeta,
  metalValueMeta,
  metalVolatilityMeta,
  metalVsMacroMeta,
  metalsBoardMeta,
  metalsCorrelationMeta,
  tokenizedGoldMeta,
  usGoldReserveMeta,
  usGoldVaultsMeta,
  // --- equities ---
  analystRatingsMeta,
  capitalStructureBarsMeta,
  cashflowTrendMeta,
  companyProfileMeta,
  earningsCalendarMeta,
  earningsCountdownMeta,
  earningsSurpriseMeta,
  filingsFeedMeta,
  filingsMixMeta,
  financialsTrendMeta,
  fundamentalsMeta,
  institutionalOwnershipMeta,
  marginTrendMeta,
  shortVolumeBarsMeta,
  shortVolumeMeta,
  valuationMultiplesMeta,
  // --- sentiment ---
  fearGreedChartMeta,
  fearGreedMeta,
  newsFeedMeta,
  predictionMarketBarsMeta,
  predictionMarketScatterMeta,
  predictionMarketsBubbleMeta,
  predictionMarketsMeta,
  sentimentCalendarMeta,
  // --- portfolio ---
  portfolioAllocationMeta,
  portfolioHoldingsMeta,
  portfolioMoversMeta,
  portfolioValueBarsMeta,
  portfolioValueMeta,
  // --- tools ---
  calculatorMeta,
  clockMeta,
  countdownMeta,
  customDataMeta,
  linkGridMeta,
  marketHoursMeta,
  // --- layout ---
  dividerMeta,
  drawdyMeta,
  groupMeta,
  headingMeta,
  heroNumberMeta,
  imageGalleryMeta,
  imageMeta,
  noteMeta,
  quoteMeta,
  videoMeta,
  // --- games ---
  dinoGameMeta,
  flappyBirdMeta,
  snakeMeta,
];

/**
 * Every renderable frame's metadata — the full set the runtime registers (the
 * React-free twin of `allFrames`), in contrast to `frameMetas` above, which is
 * the *curated* subset the AI catalogue + CLI/skill expose so the generating
 * agent only picks data/market frames. The runtime must render every meta (a
 * human adds games/journal/tools/layout frames from the editor palette, and
 * saved specs reference them), so the runtime registry builds from THIS list.
 * Keep in lockstep with `allFrames` / `frameLoaders` — the parity test in
 * `registry-parity.test.ts` fails the build if they drift.
 */
export const allFrameMetas: FrameMeta[] = [
  ...frameMetas,
  // non-agent-pickable extras — alphabetical, insert in order
  breakevenMeta,
  breathingMeta,
  checklistMeta,
  dayMeterMeta,
  diceMeta,
  holidayCalendarMeta,
  journalLogMeta,
  journalOpenMeta,
  journalResultsMeta,
  journalScoreMeta,
  marqueeMeta,
  pomodoroMeta,
  returnsProjectorMeta,
  riskRewardMeta,
  rulesCardMeta,
  sessionProgressMeta,
  spotifyEmbedMeta,
  stopwatchMeta,
];
