/**
 * Emits one uniform `<frame>.stories.tsx` per frame into src/stories/.
 *
 * Frame discovery is React-free: `@zframes/frames/schemas` exports every frame's
 * meta individually (the `frameMetas` array is only a 58-frame curated subset, so
 * we enumerate the module's exports instead to cover all 76). FRAME_CATEGORIES
 * comes from the React-free `@zframes/core/frame` subpath. The generated files
 * resolve the real frame (with its component) at runtime via `allFrames.find`.
 */
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { FRAME_CATEGORIES } from "@zframes/core/frame";
import * as schemas from "@zframes/frames/schemas";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../src/stories");

const labelByKey = new Map<string, string>(
  FRAME_CATEGORIES.map((c) => [c.key, c.label]),
);

type MetaLike = { name: string; category: string };

const metas = (Object.values(schemas) as unknown[]).filter(
  (v): v is MetaLike =>
    !!v &&
    typeof v === "object" &&
    !Array.isArray(v) &&
    typeof (v as { name?: unknown }).name === "string" &&
    typeof (v as { category?: unknown }).category === "string" &&
    "schema" in (v as object),
);

function fileFor(name: string, title: string): string {
  return `// AUTO-GENERATED by scripts/gen-stories.ts — do not edit.
import type { Meta, StoryObj } from "@storybook/react-vite";
import { allFrames } from "@zframes/frames";
import {
  argTypesFor,
  baseArgs,
  canvasRender,
  variantsRender,
  statesRender,
} from "../story-factory";

const frame = allFrames.find((f) => f.name === ${JSON.stringify(name)})!;

const meta: Meta = {
  title: ${JSON.stringify(title)},
  argTypes: argTypesFor(frame),
};
export default meta;

type S = StoryObj;

export const Default: S = { args: baseArgs(frame), render: canvasRender(frame) };

export const AllVariants: S = {
  parameters: { controls: { disable: true } },
  render: variantsRender(frame),
};

export const States: S = {
  parameters: { controls: { disable: true } },
  render: statesRender(frame),
};
`;
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const sorted = [...metas].sort((a, b) => a.name.localeCompare(b.name));
for (const meta of sorted) {
  const label = labelByKey.get(meta.category) ?? meta.category;
  const title = `${label}/${meta.name}`;
  writeFileSync(
    resolve(outDir, `${meta.name}.stories.tsx`),
    fileFor(meta.name, title),
  );
}

console.log(`gen-stories: wrote ${sorted.length} story files to src/stories/`);
