// Domain kernel — re-exported from @zframes/spec so `@zframes/core` stays the
// stable public barrel (types, spec schema, frame/registry, presets, catalogue).
export * from "@zframes/spec";

export {
  FramesProvider,
  useBtcBlocks,
  useBtcFees,
  useCandles,
  useCandlesMulti,
  useCoinMarkets,
  useCoinMovers,
  useCompanyFacts,
  useCompanyFilings,
  useDailyCloseHistory,
  useDayStats,
  useDayStatsState,
  useDexVolume,
  useDexVolumeHistory,
  useDifficultyAdjustment,
  useDollarIndex,
  useFearGreed,
  useFundingHistory,
  useFxRates,
  useGlobalMarket,
  useLightningStats,
  useMids,
  useMidsState,
  useMacroSeries,
  useMempoolState,
  useMiningPools,
  useNetworkHashrate,
  useNews,
  useOnchainExtras,
  useOnchainValuation,
  useOpenInterest,
  useOptionsSummary,
  usePortfolio,
  useVolatilityIndex,
  useReferenceRates,
  useProviderFor,
  useProviders,
  useProtocolFees,
  useProtocolTvl,
  useProtocolTvlHistory,
  useFinancialStress,
  useNationalDebt,
  useShortVolume,
  useTreasuryAuctions,
  useTreasuryAverageRates,
  useTvlByChain,
  useYieldCurve,
} from "./hooks";
export { DashboardRenderer } from "./renderer";
export {
  FRAME_CSS,
  FrameContent,
  FramePatchContext,
  useFramePatch,
  type FramePatcher,
} from "./frame-content";
